In [8]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[1,1,1],[0,0,1]])

In [11]:
print("Матрица А:\n",a)
print("Матрица A транспонированная:\n",a.T)
print("Матрица обратная A:\n", np.linalg.inv(a))
print("Матрица A^2:\n", np.dot(a,a))

Матрица А:
 [[1 2 3]
 [1 1 1]
 [0 0 1]]
Матрица A транспонированная:
 [[1 1 0]
 [2 1 0]
 [3 1 1]]
Матрица обратная A:
 [[-1.  2.  1.]
 [ 1. -1. -2.]
 [ 0.  0.  1.]]
Матрица A^2:
 [[3 4 8]
 [2 3 5]
 [0 0 1]]
